name: Validate

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/blog-validate.sln
    - name: Build
      run: dotnet build src/blog-validate.sln --configuration Release --no-restore --nologo
    - name: Validate
      run: dotnet run --project src/blog-validate/blog-validate.csproj .
